# .travis.yml

language: python

matrix:
  include:
    - python: "3.6"
      env: DEPS="numpy scipy matplotlib pillow pandas!=0.18.0 scikit-image pyyaml pytables numba"  BUILD_DOCS=false
      
install: true

script: pytest